// Generated by dts-bundle v0.7.2
// Dependencies for this module:
//   ../textfield
//   Layout.d.ts

declare module 'game-ui' {
    import './Container';
    export { default as Button } from 'game-ui/Button';
    export { default as Layout } from 'game-ui/Layout';
    export { default as Padding } from 'game-ui/Padding';
    export { default as Panel } from 'game-ui/Panel';
    export { default as ProgressBar } from 'game-ui/ProgressBar';
    export { default as Scale9Grid } from 'game-ui/Scale9Grid';
}

declare module 'game-ui/Button' {
    import Scale9Grid from 'game-ui/Scale9Grid';
    import Padding from 'game-ui/Padding';
    import Layout from 'game-ui/Layout';
    import { Styles } from 'textfield';
    export interface StatContent {
        background: Scale9Grid;
        textStyle?: Styles;
    }
    export interface Stats {
        [stat: string]: StatContent;
        default: StatContent;
        down?: StatContent;
        up?: StatContent;
        over?: StatContent;
        out?: StatContent;
        disabled?: StatContent;
    }
    export enum Stat {
        default = 0,
        down = 1,
        up = 2,
        over = 3,
        out = 4,
        disabled = 5,
    }
    export default class Button extends Layout {
        constructor(stats: Stats, padding?: Padding);
        onResize(): void;
        defaultTextStyle: Styles;
        text: string;
        disabled: boolean;
        stat: Stat;
        add(stat: Stat, texture: Scale9Grid, textStyle?: Styles): void;
    }
}

declare module 'game-ui/Layout' {
    import { Container } from 'pixi.js';
    export enum Dock {
        NONE = 1,
        TOP = 2,
        BOTTOM = 4,
        LEFT = 8,
        RIGHT = 16,
        CENTER = 32,
        MIDDLE = 64,
    }
    declare module 'game-ui/index//pixi.js' {
        interface Container {
            dock: Dock;
            dockX?: number;
            dockY?: number;
            dockPivot: (x: number, y: number) => void;
        }
    }
    export default class Layout extends Container {
        protected _width: number;
        protected _height: number;
        protected _scaleX: number;
        protected _scaleY: number;
        protected _scaleXY: number;
        constructor();
        protected childDock(child: Container): void;
        protected childPositioning(): void;
        resize(width: number, height: number): void;
        width: number;
        height: number;
        scaleX: number;
        scaleY: number;
        scaleXY: number;
    }
}

declare module 'game-ui/Padding' {
    import { utils } from 'pixi.js';
    import EventEmitter = utils.EventEmitter;
    export default class Padding extends EventEmitter {
        constructor(top?: number, bottom?: number, left?: number, right?: number);
        top: number;
        bottom: number;
        left: number;
        right: number;
    }
}

declare module 'game-ui/Panel' {
    import { Texture } from 'pixi.js';
    import Layout from 'game-ui/Layout';
    export default class Panel extends Layout {
        constructor(foreground: Texture, background: Texture);
        onResize(): void;
    }
}

declare module 'game-ui/ProgressBar' {
    import { Container } from 'pixi.js';
    import Padding from 'game-ui/Padding';
    export default class ProgressBar extends Container {
        padding: Padding;
        constructor(padding?: Padding);
        percent: number;
    }
}

declare module 'game-ui/Scale9Grid' {
    import { Texture, Rectangle } from 'pixi.js';
    import Layout from 'game-ui/Layout';
    export default class Scale9Grid extends Layout {
        constructor(texture: Texture, grid9?: Rectangle);
    }
}

